---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-jenting-io-v1-projectresourcequota
  failurePolicy: Fail
  name: mprojectresourcequota.kb.io
  rules:
  - apiGroups:
    - jenting.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projectresourcequotas
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-jenting-io-v1-projectresourcequota
  failurePolicy: Fail
  name: vprojectresourcequota.kb.io
  rules:
  - apiGroups:
    - jenting.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projectresourcequotas
  sideEffects: None
