apiVersion: jenting.io/v1
kind: ProjectResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: projectresourcequota
    app.kubernetes.io/instance: projectresourcequota-sample
    app.kubernetes.io/part-of: projectresourcequota
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectresourcequota
  name: projectresourcequota-sample
spec:
  namespaces:
  - foo
  - bar
  - default
  hard:
    configmaps: 1
    cpu: "1000"
    memory: 200Gi
    pods: "10"
